# Generated by Django 3.2.4 on 2021-07-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ColorNFT', max_length=50, verbose_name='名称')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('image', models.CharField(max_length=50, verbose_name='图片地址')),
                ('ceratetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'ordering': ['updatetime'],
            },
        ),
    ]
