# Generated by Django 3.2.4 on 2021-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtest', '0002_nfttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfttoken',
            name='image',
            field=models.CharField(max_length=255, verbose_name='图片地址'),
        ),
    ]
