# Generated by Django 3.2.4 on 2021-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtest', '0003_alter_nfttoken_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfttoken',
            name='image',
            field=models.CharField(max_length=254, verbose_name='图片地址'),
        ),
    ]
